### PR TITLE
Inherit PaperOrientation from config

### PR DESCRIPTION
**Pull request by jaap**
It seems like the paper orientation does not load from the config.
Hopefully this pull-request either helps to fix it, prove me wrong or give some direction to @barryvdh to find a swift solution.

### CODE REVIEW

**Comment by erikn69** [comment]
Maybe better after here
https://github.com/barryvdh/laravel-dompdf/blob/e49e1747d71f26454d3138d36247e9f8adc724e7/src/ServiceProvider.php#L50-L53
```php
$dompdf->setPaper(
    $app['config']->get('dompdf.defines.default_paper_size', 'a4'),
    $app['config']->get('dompdf.orientation')
);
```

**Comment by systemsolutionweb** [comment]
why are you using `config` helper?, just use `$app['config']->get()`, better performance
https://github.com/barryvdh/laravel-dompdf/blob/e49e1747d71f26454d3138d36247e9f8adc724e7/src/ServiceProvider.php#L30-L31
https://github.com/barryvdh/laravel-dompdf/blob/e49e1747d71f26454d3138d36247e9f8adc724e7/src/ServiceProvider.php#L44

**Comment by systemsolutionweb** [comment]
Looks great to me 👍

**Comment by barryvdh** [comment]
Sorry, really busy ATM. Not sure why it isn't working, but I'll look into it.

**Comment by jaap** [comment]
No worries. I'll fix the merge conflict tomorrow.

**Comment by PaolaRuby** [comment]
Next time make a rebase instead of a merge

**Comment by barryvdh** [comment]
I'm not really sure why this option is there. It should just use `default_paper_orientation`. Changed in https://github.com/barryvdh/laravel-dompdf/commit/a3772cbcd50ec386298958200ce98e4ad3bb355e

**Pull request closed without merging**
