### PR TITLE
Minor correction in codeblock of readme

### PR DESCRIPTION
**Pull request by jedymatt**
The use of facade is corrected from PDF to Pdf

### CODE REVIEW

**Comment by erikn69** [comment]
Also the next example

**Comment by jedymatt** [comment]
> Better delete the `use`, because `PDF` is the alias
> 
> https://github.com/barryvdh/laravel-dompdf/blob/cdd499077e431a833ab59b2837d218c86f093969/composer.json#L41-L43

Like this?
```php
    $pdf = PDF::loadView('pdf.invoice', $data);
    return $pdf->download('invoice.pdf');
```

**Comment by erikn69** [comment]
Included on #899

**Comment by parallels999** [comment]
This was already fixed
https://github.com/barryvdh/laravel-dompdf/blob/1d47648c6cef37f715ecb8bcc5f5a656ad372e27/readme.md?plain=1#L36-L41

**Pull request closed without merging**
