### PR TITLE
Added possibility to password protect the PDF

### PR DESCRIPTION
**Pull request by Ghitu**
A password for opening the PDF can be set calling the setEncryption method.

Example:
$pdf = PDF::loadView('pdf.invoice', $data);
$pdf->setEncryption($password);
return $pdf->download('invoice.pdf');

### CODE REVIEW

**Comment by sphkress** [comment]
I have tried to apply the setEncryption directly to PDF.php in function output() before returning $this->dompdf->output();

```
    public function output()
    {
        if (!$this->rendered) {
            $this->render();
        }

        $this->dompdf->get_canvas()->get_cpdf()->setEncryption('test');
        return $this->dompdf->output();
    }
```

Result: Document was password protected, but content was not visible anymore.

**Comment by Ghitu** [comment]
@sphkress  try to set up both $userPass and $ownerPass in setEncryption()

This is the function definition:

```
 /**
     * set the encryption of the document
     * can be used to turn it on and/or set the passwords which it will have.
     * also the functions that the user will have are set here, such as print, modify, add
     *
     * @param string $userPass
     * @param string $ownerPass
     * @param array $pc
     */
    function setEncryption($userPass = '', $ownerPass = '', $pc = array()) {
   .......
   }
```

**Comment by sphkress** [comment]
I have done this before, there is no difference about the number of parameters. I always get an empty page, e.g. even with a setup like this:

`$this->dompdf->get_canvas()->get_cpdf()->setEncryption('userpass', 'ownerpass', array('print', 'copy'));`

**Comment by arturpasnik** [comment]
Why is this not in Master? I have to add it manually.

**Comment by jyotiswarup** [comment]
> I have done this before, there is no difference about the number of parameters. I always get an empty page, e.g. even with a setup like this:
> 
> `$this->dompdf->get_canvas()->get_cpdf()->setEncryption('userpass', 'ownerpass', array('print', 'copy'));`

How did you solved then?

**Comment by sujatabh90** [comment]
$this->dompdf->get_canvas()->get_cpdf()->setEncryption('test'); - this one is working when generating pdf from html.But how to make an existing pdf file password protected using dompdf

**Comment by barryvdh** [comment]
This should already be fixed.

**Pull request closed without merging**
