### PR TITLE
Uses Laravel's filesystem for save method (saving PDF file)

### PR DESCRIPTION
**Pull request by vishwajeetv**
Source code changes for using Laravel's filesystem (which is based on flysystem - an abstraction for local and remote file systems)

### CODE REVIEW

**Comment by barryvdh** [comment]
This is a breaking change.
You can just do `Storage::put($filename, $pdf->output())` if you need this.

**Comment by djoks** [comment]
Storage::put($filename, $pdf->output()) does not work.  I get an error when I try doing this.

**Comment by djoks** [comment]
Okay seems like my issue had to do with some css links in my view.

**Comment by BlackGold888** [comment]
$pdf_name = time() . ".pdf";
        $path = public_path('/orders/' . $pdf_name);
        $pdf = PDF::loadView('mail')->save($path);

**Pull request closed without merging**
