### PR TITLE
Revert "Fix setOptions method"

### PR DESCRIPTION
**Pull request by barryvdh**
Reverts barryvdh/laravel-dompdf#974

### CODE REVIEW

**Comment by cesarreyes3** [comment]
This breaks my APP when i trying to reset config file defaults, same as #793

**Comment by barryvdh** [comment]
What version worked for you? This only reverts the change from last week.

**Comment by cesarreyes3** [comment]
https://github.com/barryvdh/laravel-dompdf/releases/tag/v2.1.0

**Comment by cesarreyes3** [comment]
#1040 ??

**Pull request merged**
