### PR TITLE
Fix other options got reset when set options

### PR DESCRIPTION
**Pull request by dodaydream**
When setting the options using the code below:

```php
$this->pdf = PDF::setOptions(['enable_php' => true]); 
```

and print the options

```php
dd($this->pdf->getDomPDF()->getOptions());   
```

we can see the font dir options and other options goes back to default.

```
Dompdf\Options {#297 ▼
  -rootDir: "/Users/stanley/Dev/dompdftest/vendor/dompdf/dompdf"
  -tempDir: "/var/folders/cl/stsnb1jd7l3dfzlty1wxmbj00000gn/T"
  -fontDir: "/Users/stanley/Dev/dompdftest/vendor/dompdf/dompdf/lib/fonts"
  -fontCache: "/Users/stanley/Dev/dompdftest/vendor/dompdf/dompdf/lib/fonts"
  -chroot: array:1 [▶]
  -logOutputFile: "/var/folders/cl/stsnb1jd7l3dfzlty1wxmbj00000gn/T/log.htm"
  -defaultMediaType: "screen"
  -defaultPaperSize: "letter"
  -defaultPaperOrientation: "portrait"
  -defaultFont: "serif"
  -dpi: 96
  -fontHeightRatio: 1.1
  -isPhpEnabled: true
  -isRemoteEnabled: false
  -isJavascriptEnabled: true
  -isHtml5ParserEnabled: false
  -isFontSubsettingEnabled: true
  -debugPng: false
  -debugKeepTemp: false
  -debugCss: false
  -debugLayout: false
  -debugLayoutLines: true
  -debugLayoutBlocks: true
  -debugLayoutInline: true
  -debugLayoutPaddingBox: true
  -pdfBackend: "CPDF"
  -pdflibLicense: ""
}
```

After opened an [issue on dompdf](https://github.com/dompdf/dompdf/issues/2690), asking how to set a single options, i modified the code to this and the output became normal again.

```
Dompdf\Options {#283 ▼
  -rootDir: "/Users/stanley/Dev/dompdftest/vendor/dompdf/dompdf"
  -tempDir: "/var/folders/cl/stsnb1jd7l3dfzlty1wxmbj00000gn/T"
  -fontDir: "/Users/stanley/Dev/dompdftest/storage/fonts"
  -fontCache: "/Users/stanley/Dev/dompdftest/storage/fonts"
  -chroot: array:1 [▶]
  -logOutputFile: "/var/folders/cl/stsnb1jd7l3dfzlty1wxmbj00000gn/T/log.htm"
  -defaultMediaType: "screen"
  -defaultPaperSize: "a4"
  -defaultPaperOrientation: "portrait"
  -defaultFont: "serif"
  -dpi: 96
  -fontHeightRatio: 1.1
  -isPhpEnabled: true
  -isRemoteEnabled: true
  -isJavascriptEnabled: true
  -isHtml5ParserEnabled: false
  -isFontSubsettingEnabled: false
  -debugPng: false
  -debugKeepTemp: false
  -debugCss: false
  -debugLayout: false
  -debugLayoutLines: true
  -debugLayoutBlocks: true
  -debugLayoutInline: true
  -debugLayoutPaddingBox: true
  -pdfBackend: "CPDF"
  -pdflibLicense: ""
}
```

### CODE REVIEW

**Comment by angeljqv** [comment]
Looks like there is nobody for reviews, almost abandoned

**Comment by angeljqv** [comment]
Looks like there is nobody for reviews, almost abandoned

**Comment by dodaydream** [comment]
> Looks like there is nobody for reviews, almost abandoned

Hmmm... I would be really appreciated if someone could review this pr. Both `laravel-dompdf` and `laravel-invoices` are great libraries. However, it would be a pity if not support UTF-8 characters.

**Comment by erikn69** [comment]
This is a breaking change if somebody expects  goes back to default options as already works

I think that is better a new method like `updateOptions`, `appendOptions` or other name
```php
public function appendOptions(array $options): self
{
    $opts = $this->dompdf->getOptions();

    foreach ($options as $key=>$value) {
        $opts->set($key, $value);
    }

    return $this;
}
```

**Comment by dodaydream** [comment]
Thanks for the reply. I agree changing this method might break the behaviour for somebody uses this library. However, as stated [in the comment](https://github.com/barryvdh/laravel-dompdf/blob/cdd499077e431a833ab59b2837d218c86f093969/src/PDF.php#L138) of this method, `setOptions()` will "Set/Change an option in DomPdf" instead of replacing them, and changing the implementation will align the actual behaviour with the comment.

**Comment by erikn69** [comment]
Better change the comment

**Comment by barryvdh** [comment]
Hmm I agree the comment is misleading, but I want to avoid changing behavior. I added the setOption here: https://github.com/barryvdh/laravel-dompdf/commit/00443b33aff68f9e996de536c8f62735c4042131
Should behave as you expect 

```php
->setOption(['temp_dir' => 'test_dir']);

->setOption('temp_dir', 'test_dir');
```

**Pull request closed without merging**
